name: mobile_anwendungen
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  easy_localization: ^3.0.1
  rxdart: ^0.27.0
  intl: ^0.19.0 # Diese Version ist festgelegt durch flutter_localizations
  go_router: ^13.2.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.1.0
  freezed: ^2.1.1
  cupertino_icons: ^1.0.6
  path_provider: ^2.0.0
  path: ^1.8.0
  collection: ^1.18.0
  adaptive_theme: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  go_router_builder: any
  build_verify: any
  objectbox_generator: any
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.1.1
  klutter: ^3.0.2

dependency_overrides:
  intl: ^0.19.0
  dart_console: ^1.2.0

flutter:
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
  uses-material-design: true

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-Regular.ttf
