name: mobile_anwendungen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  easy_localization: ^3.0.1
  rxdart: ^0.27.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/lang/
  uses-material-design: true

