// Mocks generated by Mockito 5.4.4 from annotations
// in mobile_anwendungen/test/unitTests/ui/onboarding/onboarding_statistics_test/onboarding_statistics_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i4;
import 'package:mobile_anwendungen/database/database.dart' as _i2;
import 'package:mobile_anwendungen/domain/habit/onboarding_default_repository.dart'
    as _i6;
import 'package:mobile_anwendungen/domain/navigation/go_router_navigation_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoRouterNavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoRouterNavigationService extends _i1.Mock
    implements _i3.GoRouterNavigationService {
  MockGoRouterNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void pop<T>({T? data}) => super.noSuchMethod(
        Invocation.method(
          #pop,
          [],
          {#data: data},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showHabitDetail(
    int? id,
    _i4.BuildContext? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showHabitDetail,
          [
            id,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showConfirmDeleteAlert(_i5.VoidCallback? onConfirm) =>
      super.noSuchMethod(
        Invocation.method(
          #showConfirmDeleteAlert,
          [onConfirm],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showSnackBar(String? message) => super.noSuchMethod(
        Invocation.method(
          #showSnackBar,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showOnboardingHabits(_i4.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #showOnboardingHabits,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showOnboardingStatistics(_i4.BuildContext? context) =>
      super.noSuchMethod(
        Invocation.method(
          #showOnboardingStatistics,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showHome(_i4.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #showHome,
          [context],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OnboardingDefaultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingDefaultRepository extends _i1.Mock
    implements _i6.OnboardingDefaultRepository {
  MockOnboardingDefaultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.Database);

  @override
  void completeOnboarding() => super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isCompletedOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #isCompletedOnboarding,
          [],
        ),
        returnValue: false,
      ) as bool);
}
