// Mocks generated by Mockito 5.4.4 from annotations
// in mobile_anwendungen/test/unitTests/domain/habit/habit_default_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_anwendungen/database/database.dart' as _i2;
import 'package:mobile_anwendungen/database/model/database_habit.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i2.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.DatabaseHabit> listHabits() => (super.noSuchMethod(
        Invocation.method(
          #listHabits,
          [],
        ),
        returnValue: <_i4.DatabaseHabit>[],
      ) as List<_i4.DatabaseHabit>);

  @override
  void upsertHabit(_i4.DatabaseHabit? habit) => super.noSuchMethod(
        Invocation.method(
          #upsertHabit,
          [habit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void completeHabit(_i4.DatabaseHabit? habit) => super.noSuchMethod(
        Invocation.method(
          #completeHabit,
          [habit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unCompleteHabit(_i4.DatabaseHabit? habit) => super.noSuchMethod(
        Invocation.method(
          #unCompleteHabit,
          [habit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reorderHabit(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderHabit,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteHabit(_i4.DatabaseHabit? habit) => super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [habit],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int nextIndex() => (super.noSuchMethod(
        Invocation.method(
          #nextIndex,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.DatabaseHabit? getById(int? id) => (super.noSuchMethod(Invocation.method(
        #getById,
        [id],
      )) as _i4.DatabaseHabit?);

  @override
  void completeOnboarding() => super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isCompletedOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #isCompletedOnboarding,
          [],
        ),
        returnValue: false,
      ) as bool);
}
